CREATE TABLE Users(
    id NUMBER GENERATEd ALWAYS AS IDENTITY PRIMARY KEY,
    role VARCHAR2(20) CHECK(role IN ('ADMIN', 'WORKER')) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK(is_active IN (0,1)) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Suppliers(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    street VARCHAR2(150),
    city VARCHAR2(80),
    country VARCHAR2(80),
    email VARCHAR(255),
    phone VARCHAR(15),
    is_active NUMBER(1) DEFAULT 1 CHECK(is_active IN (0, 1)) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Warehouses(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    street VARCHAR2(150),
    city VARCHAR2(80),
    country VARCHAR2(80),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

