CREATE TABLE Users(
    id NUMBER PRIMARY KEY,
    role VARCHAR2(20) CHECK(role IN ('ADMIN', 'WORKER')) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK(is_active IN (0,1)) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 

CREATE SEQUENCE seq_users START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER tgr_users_id
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
    :NEW.id :=seq_users.NEXTVAL;
END;
/

CREATE TABLE Suppliers(
    id NUMBER PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    street VARCHAR2(150),
    city VARCHAR2(80),
    country VARCHAR2(80),
    email VARCHAR2(255),
    phone VARCHAR2(15),
    is_active NUMBER(1) DEFAULT 1 CHECK(is_active IN (0, 1)) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);  
CREATE SEQUENCE seq_suppliers START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_suppliers_id 
BEFORE INSERT ON Suppliers
FOR EACH ROW 
BEGIN
    :NEW.id :=seq_suppliers.NEXTVAL;
END;
/

CREATE TABLE Warehouses(
    id NUMBER PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    street VARCHAR2(150),
    city VARCHAR2(80),
    country VARCHAR2(80),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 
CREATE SEQUENCE seq_warehouses START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_warehouses_id 
BEFORE INSERT ON Warehouses
FOR EACH ROW 
BEGIN
    :NEW.id :=seq_warehouses.NEXTVAL;
END;
/